// Masukkan API Key kamu di sini
const API_KEY = "AQ.Ab8RN6IZBdBtZZ3oPGoRQzZ6JP17URVkU_KiJPReAH6ZzoHIbg"; 

// Ganti URL ini dengan URL Endpoint AI yang kamu gunakan (misal: endpoint OpenAI, OpenRouter, dll)
// Contoh di bawah menggunakan standar struktur API OpenAI
const API_URL = "https://api.openai.com/v1/chat/completions"; 

const chatBox = document.getElementById("chat-box");
const userInput = document.getElementById("user-input");

function handleKeyPress(event) {
    if (event.key === "Enter") {
            sendMessage();
                }
                }

                async function sendMessage() {
                    const text = userInput.value.trim();
                        if (text === "") return;

                            // Tampilkan pesan user
                                addMessage(text, "user-message");
                                    userInput.value = "";

                                        // Tampilkan indikator loading dari Rem
                                            const loadingId = addMessage("Rem sedang berpikir...", "ai-message");

                                                try {
                                                        const response = await fetch(API_URL, {
                                                                    method: "POST",
                                                                                headers: {
                                                                                                "Content-Type": "application/json",
                                                                                                                "Authorization": `Bearer ${API_KEY}`
                                                                                                                            },
                                                                                                                                        body: JSON.stringify({
                                                                                                                                                        model: "gpt-3.5-turbo", // Sesuaikan model dengan provider AI kamu
                                                                                                                                                                        messages: [
                                                                                                                                                                                            { role: "system", content: "Kamu adalah Rem dari anime Re:Zero. Kamu sangat setia, sopan, berbicara dengan lembut, dan selalu menyebut dirimu 'Rem' (bukan 'saya' atau 'aku')." },
                                                                                                                                                                                                                { role: "user", content: text }
                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                            const data = await response.json();
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                            // Hapus pesan loading
                                                                                                                                                                                                                                                                                    document.getElementById(loadingId).remove();

                                                                                                                                                                                                                                                                                            if (data.choices && data.choices.length > 0) {
                                                                                                                                                                                                                                                                                                        const aiReply = data.choices[0].message.content;
                                                                                                                                                                                                                                                                                                                    addMessage(aiReply, "ai-message");
                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                        addMessage("Maaf, Rem tidak mengerti respons dari server...", "ai-message");
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                            document.getElementById(loadingId).remove();
                                                                                                                                                                                                                                                                                                                                                                    addMessage("Maaf, koneksi Rem terputus atau terjadi kesalahan sistem.", "ai-message");
                                                                                                                                                                                                                                                                                                                                                                            console.error("Error:", error);
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                function addMessage(text, className) {
                                                                                                                                                                                                                                                                                                                                                                                    const messageDiv = document.createElement("div");
                                                                                                                                                                                                                                                                                                                                                                                        messageDiv.className = `message ${className}`;
                                                                                                                                                                                                                                                                                                                                                                                            messageDiv.innerText = text;
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    // Memberikan ID unik untuk keperluan menghapus pesan loading
                                                                                                                                                                                                                                                                                                                                                                                                        const id = "msg-" + Date.now();
                                                                                                                                                                                                                                                                                                                                                                                                            messageDiv.id = id;
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    chatBox.appendChild(messageDiv);
                                                                                                                                                                                                                                                                                                                                                                                                                        chatBox.scrollTop = chatBox.scrollHeight; // Auto scroll ke bawah
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                return id;
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                